[package]
name = "tele"
version = "0.1.4"
authors = ["Philip Koperski <philip@pretzelwagon.com>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
cli-table = "0.2"
kettle = "0.2.1"
