[package]
name = "tele"
version = "0.1.3"
authors = ["Philip Koperski <philip@pretzelwagon.com>"]
edition = "2018"

[dependencies]
clap = "2"
dirs = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
cli-table = "0.2"
